
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SLAVEDIC_H
#define SLAVEDIC_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 slavedic_valueRangeTest (UNS8 typeValue, void * value);
const CONSTSTORE indextable * slavedic_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data slavedic_Data;
extern UNS8 var0;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS16 var1;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS32 var2;		/* Mapped at index 0x2002, subindex 0x00*/
extern INTEGER32 var3;		/* Mapped at index 0x2003, subindex 0x00*/
extern INTEGER16 var4;		/* Mapped at index 0x2004, subindex 0x00*/
extern char var5[10];		/* Mapped at index 0x2005, subindex 0x00*/

#endif // SLAVEDIC_H
